version: "3.7"

services:
  nopcommerce:
    image: nopcommerceteam/nopcommerce
    hostname: nopcommerce
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80:80"
    networks:
      nopcommerce_net:
    healthcheck:
      test: curl --fail -s http://localhost/healthcheck || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    restart: always
    depends_on:
      - mssql


  mssql:
    image: mcr.microsoft.com/mssql/server
    hostname: mssql
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      nopcommerce_net:
    healthcheck:
      test: sqlcmd -S mssql -U SA -P 'P@ssw0rd' -Q 'Select TOP 1 name from master..sysdatabases'
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: always
    volumes:
      - nopcommerce_data:/var/opt/mssql
volumes:
  nopcommerce_data:

networks:
  nopcommerce_net: